"""Gate 0A: official FedTA <-> FedSMTA baseline parity test.

Gate 0B (resume regression) only proves "our code continuous == our code
resumed". This test proves the stronger statement:

    FedSMTA --method fedta --no_instrumentation  ==  Official FedTA

It runs the OFFICIAL FedTA repo in-process through a generated driver
script (the official repo has no checkpoint mechanism, so the driver
exports the final state right after myServer.start()), runs the fork with
the frozen short-parity configuration, and compares:

  server model / global head / global protos / temp protos / server prompt,
  per-client heads / tail-anchor key / anchor_pool / full tail-anchor state
  / prompts, fix_keys, the federated outer split manifest (raw indices +
  class masks) and the inner 70/30 split indices per (client, task).

PASS requires D = 0 EXACTLY (no floating-point tolerance): if tiny nonzero
diffs appear, first suspect GPU/operator nondeterminism and rerun — do NOT
loosen the tolerance to make it pass.

v1 limitations (documented, not gating):
  - accuracy is not compared directly: D = 0 over all model states and both
    splits implies identical evaluation outputs;
  - RNG states cannot be compared (the official repo saves nothing).

Writes metrics/official_fedta_parity.json under --work_dir.

Prerequisites:
  - --official_repo: a local clone of the official FedTA repo, with its
    dataset reachable (if the official spliter hardcodes the dataset path,
    prepare that path; any dropped kwarg is reported in the JSON);
  - pretrain_model/ViT-B_16.npz under the official repo;
  - same GPU for both sides; --official_python if the official repo needs
    a different environment.

Usage (ON THE SERVER, from the repo root):

  python tests/test_official_fedta_parity.py \
      --official_repo /path/to/official_FedTA \
      --data_path ./local_datasets
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import torch

from test_resume_regression import (
    REPO_ROOT, max_diff, state_dict_diff, protos_diff, deep_equal, hash_obj,
    require_outer_manifest,
)

# config modules tried in order inside the official repo (the fork renamed
# config/cifar100.py -> config/datasets_delay.py; override with
# --config_module if the official layout differs)
CONFIG_MODULE_CANDIDATES = ["config.cifar100", "config.cifar100_delay"]
VIT_MODULE_CANDIDATES = [
    "Models.vision_transformer__l2p",
    "Models.vision_transformer_l2p",
    "models.vision_transformer__l2p",
]

# kwargs the official config MUST define (experiment-defining parameters).
# A missing key means config drift -> fail loudly, never silently
# misconfigure the parity run.
STRICT_OVERRIDE_KEYS = [
    "client_num", "task_num", "private_class_num", "global_epoch",
    "local_epoch", "batch_size", "seed", "lr", "method", "device",
    "model", "model_name", "input_size",
]
# kwargs the official config may legitimately lack (the official code may
# hardcode the same value, e.g. threshold=0.25 / surrogate_num=20): they are
# force-set on the namespace anyway, and their absence from the official
# config is reported in the parity JSON instead of failing the run.
LENIENT_OVERRIDE_KEYS = ["data_path", "surrogate_num", "threshold"]


# ---------------------------------------------------------------------------
# driver executed INSIDE the official repo (cwd = official repo root)
# ---------------------------------------------------------------------------
DRIVER_SOURCE = r'''"""Gate 0A parity driver (GENERATED by
tests/test_official_fedta_parity.py - do not edit by hand).

Replicates the official FedTA main() flow with the frozen short-parity
configuration, then dumps the final training state in the FedSMTA
checkpoint format. The official repo has no checkpoint mechanism (no
torch.save in its training loop), so the state is exported in-process
right after myServer.start().
"""
import argparse
import inspect
import json
import random
import sys

import numpy as np

# cuBLAS determinism env must be set before torch initializes cuBLAS
# (mirrors the fork's --deterministic mode; both sides run deterministic)
import os
os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")

import torch
from torch.backends import cudnn

cudnn.deterministic = True
cudnn.benchmark = False
torch.use_deterministic_algorithms(True, warn_only=True)
print("[parity-driver] deterministic mode ON "
      "(cudnn.deterministic=True, benchmark=False)")


def _import_first(candidates, what):
    errors = []
    for name in candidates:
        try:
            return __import__(name, fromlist=["*"]), name
        except Exception as exc:
            errors.append("  %s: %r" % (name, exc))
    raise SystemExit("[parity-driver] cannot import %s; tried:\n%s"
                     % (what, "\n".join(errors)))


def _module_state(module):
    if module is None:
        return None
    return {k: v.detach().cpu() for k, v in module.state_dict().items()}


# ---------------------------------------------------------------------------
# Patch random_split BEFORE Models.Client_DF is imported (it binds
# random_split at module import time). The official repo does not record
# the inner 70/30 split indices; the fork stores them as
# data_split_indices, so we capture the same content here: per (client,
# task) the train/test Subset.indices.
# ---------------------------------------------------------------------------
_inner_splits = {}
_split_ctx = {"ctx": None}
_orig_random_split = torch.utils.data.random_split


def _recording_random_split(dataset, *split_args, **split_kwargs):
    subsets = _orig_random_split(dataset, *split_args, **split_kwargs)
    ctx = _split_ctx["ctx"]
    if ctx is not None and len(subsets) == 2:
        cid, tid = ctx
        _inner_splits.setdefault(str(cid), {})[str(tid)] = {
            "train": [int(x) for x in subsets[0].indices],
            "test": [int(x) for x in subsets[1].indices],
        }
    return subsets


torch.utils.data.random_split = _recording_random_split


def main():
    cli = argparse.ArgumentParser()
    cli.add_argument("--payload", required=True)
    with open(cli.parse_args().payload, encoding="utf-8") as f:
        payload = json.load(f)

    # ---- official config: defaults + frozen short-parity overrides ----
    cfg_mod, cfg_name = _import_first(payload["config_module_candidates"],
                                      "official config module")
    parser = argparse.ArgumentParser("official FedTA defaults")
    try:
        cfg_mod.get_args_parser(parser)
    except TypeError:
        # older pattern: get_args_parser() builds and returns its own parser
        parser = cfg_mod.get_args_parser()
    args = parser.parse_args([])

    strict = payload["strict_overrides"]
    missing = [k for k in strict if not hasattr(args, k)]
    if missing:
        available = sorted(vars(args))
        raise SystemExit(
            "[parity-driver] official config lacks argument(s): %s\n"
            "available keys:\n  %s"
            % (", ".join(sorted(missing)), "\n  ".join(available)))
    for key, value in strict.items():
        setattr(args, key, value)

    # lenient keys are force-set even if the official config does not
    # define them (the replicated flow below reads them from the
    # namespace); absence is reported so config drift stays visible
    lenient_absent = []
    for key, value in payload["lenient_overrides"].items():
        if not hasattr(args, key):
            lenient_absent.append(key)
        setattr(args, key, value)

    # ---- official modules (imports resolve against the official repo) ----
    _import_first(payload["vit_module_candidates"],
                  "official ViT prompt module")
    from timm.models import create_model
    from data.iCIFAR100c import iCIFAR100c
    from data.cifar100_subset_spliter import cifar100_Data_Spliter
    from Models.Server_DF import Server_DF
    from Models.Client_DF import Client_DF

    # tag each inner random_split with (client, task)
    if not hasattr(Client_DF, "get_data"):
        raise SystemExit("[parity-driver] official Client_DF has no "
                         "get_data(); the official code layout differs "
                         "from the assumed one")
    _orig_get_data = Client_DF.get_data

    def _ctx_get_data(self, task_id):
        _split_ctx["ctx"] = (self.id, task_id)
        try:
            return _orig_get_data(self, task_id)
        finally:
            _split_ctx["ctx"] = None

    Client_DF.get_data = _ctx_get_data

    # ---- replicate the official main() flow (RNG-consumption order
    #      preserved: seed -> create_model default_cfg -> partition ->
    #      models -> server) ----
    device = torch.device(args.device)
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    random.seed(args.seed)
    pretrained_cfg = create_model(args.model).default_cfg
    pretrained_cfg['file'] = 'pretrain_model/ViT-B_16.npz'

    # kwargs filtered by the official spliter signature (the fork added
    # data_path; an older official spliter may hardcode the dataset path)
    spliter_params = {
        "client_num": args.client_num,
        "task_num": args.task_num,
        "private_class_num": args.private_class_num,
        "input_size": args.input_size,
        "data_path": args.data_path,
    }
    sig_params = inspect.signature(
        cifar100_Data_Spliter.__init__).parameters
    spliter_kwargs = {k: v for k, v in spliter_params.items()
                      if k in sig_params}
    dropped_spliter = sorted(set(spliter_params) - set(spliter_kwargs))
    if dropped_spliter:
        print("[parity-driver] note: official spliter does not accept: %s "
              "(the official hardcoded convention is used)"
              % ", ".join(dropped_spliter))

    client_data, client_mask = \
        cifar100_Data_Spliter(**spliter_kwargs).random_split()
    surro_data, test_data = \
        cifar100_Data_Spliter(**spliter_kwargs).process_testdata(
            args.surrogate_num)
    surro_data = iCIFAR100c(subset=surro_data)
    args.nb_classes = 100

    print("Creating original model: %s" % args.model)
    original_model = create_model(
        args.model, pretrained=True, pretrained_cfg=pretrained_cfg,
        num_classes=args.nb_classes, drop_rate=args.drop,
        drop_path_rate=args.drop_path, drop_block_rate=None)

    print("Creating model: %s" % args.model)
    model = create_model(
        args.model, pretrained=True, pretrained_cfg=pretrained_cfg,
        num_classes=args.nb_classes, drop_rate=args.drop,
        drop_path_rate=args.drop_path, drop_block_rate=None,
        prompt_length=args.length, embedding_key=args.embedding_key,
        prompt_init=args.prompt_key_init, prompt_pool=True,
        prompt_key=args.prompt_key, pool_size=args.size,
        top_k=args.top_k, batchwise_prompt=args.batchwise_prompt,
        prompt_key_init=args.prompt_key_init, head_type=args.head_type,
        use_prompt_mask=args.use_prompt_mask)

    original_model.to(device)
    model.to(device)

    if args.freeze:
        for n, p in model.named_parameters():
            if n.startswith(tuple(args.freeze)):
                p.requires_grad = False

    # kwargs filtered by the official Server_DF signature (the fork added
    # run_manager=); core kwargs MUST exist or the layout differs
    server_kwargs = dict(
        id='Server', origin_model=original_model, model_name=args.model_name,
        client_num=args.client_num, task_num=args.task_num,
        subset=client_data, class_mask=client_mask, lr=args.lr,
        global_epoch=args.global_epoch, local_epoch=args.local_epoch,
        batch_size=args.batch_size, device=args.device, method=args.method,
        threshold=args.threshold, surrogate_data=surro_data,
        test_data=None, args=args, model=model)
    sig_params = inspect.signature(Server_DF.__init__).parameters
    core = ["id", "origin_model", "model_name", "client_num", "task_num",
            "subset", "class_mask", "lr", "global_epoch", "local_epoch",
            "batch_size", "device", "method", "threshold", "surrogate_data",
            "test_data", "args", "model"]
    missing_core = [k for k in core if k not in sig_params]
    if missing_core:
        raise SystemExit(
            "[parity-driver] official Server_DF.__init__ lacks core "
            "kwarg(s): %s\nsignature: %s"
            % (", ".join(missing_core), sig_params))
    dropped_server = sorted(set(server_kwargs) - set(sig_params))
    if dropped_server:
        print("[parity-driver] note: official Server_DF does not accept: %s"
              % ", ".join(dropped_server))
    server_kwargs = {k: v for k, v in server_kwargs.items()
                     if k in sig_params}

    myServer = Server_DF(**server_kwargs)
    myServer.start()

    # ---- export the final state in the FedSMTA checkpoint format ----
    manifest = {}
    for i in range(myServer.client_num):
        per_task = {}
        for t in range(myServer.task_num):
            subset = myServer.client_data[i][t]
            per_task[str(t)] = {
                "raw_indices": [int(x) for x in subset.indices],
                "class_mask": [int(c) for c in myServer.class_mask[i][t]],
            }
        manifest[str(i)] = per_task

    clients_dump = []
    for c in myServer.clients:
        clients_dump.append({
            "id": c.id,
            "task_id": c.task_id,
            "tail_anchor_model": _module_state(c.model),
            "prompts": _module_state(getattr(c, "prompts", None)),
            "heads": [_module_state(h) for h in c.heads],
        })

    state = {
        "completed_round": myServer.task_num * myServer.global_epoch - 1,
        "server_model": _module_state(myServer.model),
        "global_head": _module_state(myServer.global_head),
        "global_protos": getattr(myServer, "global_protos", None),
        "temp_protos": getattr(myServer, "temp_protos", None),
        "fix_keys": list(getattr(myServer, "fix_keys", []) or []),
        "server_prompt": _module_state(getattr(myServer, "prompt", None)),
        "clients": clients_dump,
        "inner_splits": _inner_splits,
        "outer_split_manifest": manifest,
        "config_module": cfg_name,
        "dropped_spliter_kwargs": dropped_spliter,
        "dropped_server_kwargs": dropped_server,
        "lenient_overrides_absent_from_config": lenient_absent,
        "official_args": dict(vars(args)),
    }
    torch.save(state, payload["dump_path"])
    print("[parity-driver] final state dumped to %s" % payload["dump_path"])


if __name__ == "__main__":
    main()
'''


def parse_args():
    p = argparse.ArgumentParser("Gate 0A: official FedTA parity test")
    p.add_argument("--official_repo", required=True,
                   help="path to a local clone of the OFFICIAL FedTA repo")
    p.add_argument("--official_python", default="",
                   help="python interpreter for the official repo (default: "
                        "the interpreter running this test; set when the "
                        "official repo needs a different environment)")
    p.add_argument("--config_module", default="",
                   help="override the config module auto-detection inside "
                        "the official repo (default: try %s)"
                        % ", ".join(CONFIG_MODULE_CANDIDATES))
    p.add_argument("--data_name", default="cifar100", choices=["cifar100"],
                   help="Gate 0A v1 is cifar100-only (the frozen baseline)")
    p.add_argument("--data_path", default="./local_datasets",
                   help="dataset root for the fork side (and for the "
                        "official side if its spliter accepts data_path)")
    p.add_argument("--rounds", default=4, type=int,
                   help="total rounds; must equal task_num*global_epoch "
                        "(the official repo always runs the full task loop)")
    p.add_argument("--global_epoch", default=2, type=int)
    p.add_argument("--task_num", default=2, type=int)
    p.add_argument("--local_epoch", default=2, type=int,
                   help="keep small: this only tests parity mechanics")
    p.add_argument("--client_num", default=5, type=int)
    p.add_argument("--private_class_num", default=15, type=int)
    p.add_argument("--batch_size", default=16, type=int)
    p.add_argument("--surrogate_num", default=20, type=int)
    p.add_argument("--threshold", default=0.25, type=float)
    p.add_argument("--lr", default=0.001, type=float)
    p.add_argument("--seed", default=42, type=int)
    p.add_argument("--device", default="cuda")
    p.add_argument("--work_dir", default="output/regression", type=Path)
    p.add_argument("--method", default="fedta")
    p.add_argument("--keep_driver", action="store_true",
                   help="keep the generated driver/payload/dump files in "
                        "the official repo for debugging")
    return p.parse_args()


def run_main(extra):
    cmd = [sys.executable, "main.py", "datasets_delay"] + extra
    print("+", " ".join(cmd), flush=True)
    proc = subprocess.run(cmd, cwd=str(REPO_ROOT))
    if proc.returncode != 0:
        raise RuntimeError(f"command failed: {' '.join(cmd)}")


def main():
    args = parse_args()
    total = args.task_num * args.global_epoch
    if args.rounds != total:
        raise SystemExit(
            f"--rounds must equal task_num*global_epoch ({total}): the "
            "official repo always runs its full task loop, so the fork "
            "side must run the same number of rounds")

    official_repo = Path(args.official_repo).expanduser().resolve()
    for rel in ("main.py", "Models", "config"):
        if not (official_repo / rel).exists():
            raise SystemExit(
                f"--official_repo does not look like the official FedTA "
                f"repo: missing {rel!r} under {official_repo}")
    official_python = args.official_python or sys.executable

    tag = f"{os.getpid()}_{int(time.time())}"
    driver_path = official_repo / f"_parity_driver_{tag}.py"
    payload_path = official_repo / f"_parity_payload_{tag}.json"
    dump_path = official_repo / f"_parity_dump_{tag}.pth"

    strict_overrides = {
        "client_num": args.client_num,
        "task_num": args.task_num,
        "private_class_num": args.private_class_num,
        "global_epoch": args.global_epoch,
        "local_epoch": args.local_epoch,
        "batch_size": args.batch_size,
        "seed": args.seed,
        "lr": args.lr,
        "method": args.method,
        "device": args.device,
        "model": "vit_base_patch16_224",
        "model_name": "Tail_Anchor",
        "input_size": 224,
    }
    lenient_overrides = {
        "data_path": args.data_path,
        "surrogate_num": args.surrogate_num,
        "threshold": args.threshold,
    }
    assert sorted(strict_overrides) == sorted(STRICT_OVERRIDE_KEYS)
    assert sorted(lenient_overrides) == sorted(LENIENT_OVERRIDE_KEYS)

    payload = {
        "config_module_candidates": (
            [args.config_module] if args.config_module
            else CONFIG_MODULE_CANDIDATES),
        "vit_module_candidates": VIT_MODULE_CANDIDATES,
        "strict_overrides": strict_overrides,
        "lenient_overrides": lenient_overrides,
        "dump_path": str(dump_path),
    }
    driver_path.write_text(DRIVER_SOURCE, encoding="utf-8")
    payload_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    run_dir = (args.work_dir / args.data_name / args.method
               / "parity_fedta" / f"seed_{args.seed}")
    if run_dir.exists():
        print(f"[cleanup] removing previous test run dir {run_dir}")
        shutil.rmtree(run_dir)

    passed = False
    try:
        # ---------- side 1: the OFFICIAL repo (in-process driver) ----------
        cmd = [official_python, driver_path.name,
               "--payload", payload_path.name]
        print(f"[official] cwd={official_repo}")
        print("+", " ".join(cmd), flush=True)
        proc = subprocess.run(cmd, cwd=str(official_repo))
        if proc.returncode != 0:
            raise RuntimeError("official-repo parity driver failed")

        # ---------- side 2: the fork (fedta, observers off) ----------
        base = ["--data_name", args.data_name,
                "--data-path", args.data_path,
                "--seed", str(args.seed), "--device", args.device,
                "--client_num", str(args.client_num),
                "--task_num", str(args.task_num),
                "--private_class_num", str(args.private_class_num),
                "--global_epoch", str(args.global_epoch),
                "--local_epoch", str(args.local_epoch),
                "--batch-size", str(args.batch_size),
                "--surrogate_num", str(args.surrogate_num),
                "--threshold", str(args.threshold),
                "--lr", str(args.lr),
                "--method", args.method,
                "--deterministic", "--no_instrumentation",
                "--save_every", "1",
                "--output_dir", str(args.work_dir),
                "--max_rounds", str(args.rounds)]
        run_main(base + ["--run_name", "parity_fedta"])

        dump = torch.load(dump_path, map_location="cpu", weights_only=False)
        ckpt = torch.load(run_dir / "checkpoints" / "latest.pth",
                          map_location="cpu", weights_only=False)

        # ---------- Gate 0A seals (hard asserts, no vacuous pass) ----------
        assert ckpt["args"].get("no_instrumentation") is True, (
            "fork checkpoint must record no_instrumentation=True: the "
            "parity baseline is FedTA + checkpoint only")
        assert ckpt["args"].get("deterministic") is True, (
            "fork checkpoint must record deterministic=True (the official "
            "driver runs cudnn.deterministic=True as well)")
        assert int(ckpt["completed_round"]) == args.rounds - 1, (
            f"fork run must complete all {args.rounds} rounds "
            f"(completed_round={ckpt['completed_round']})")
        ids_fork = [c["id"] for c in ckpt["clients"]]
        ids_official = [c["id"] for c in dump["clients"]]
        assert ids_fork == ids_official, (
            f"client id order differs: fork={ids_fork}, "
            f"official={ids_official}")
        # both manifests must exist and be non-empty (no {} == {} pass)
        outer_fork = require_outer_manifest(ckpt, str(run_dir))
        outer_official = dump["outer_split_manifest"]
        assert isinstance(outer_official, dict) and outer_official, (
            "official dump missing outer_split_manifest (driver bug)")

        # ---------- state comparison (goal: D = 0 everywhere) ----------
        head_diffs = [state_dict_diff(ckpt["global_head"],
                                      dump["global_head"])]
        key_diffs, anchor_diffs, ta_diffs, cprompt_diffs = [], [], [], []
        for cf, co in zip(ckpt["clients"], dump["clients"]):
            assert len(cf["heads"]) == len(co["heads"]), (
                f"client {cf['id']}: head count differs "
                f"(fork={len(cf['heads'])}, official={len(co['heads'])})")
            for hf, ho in zip(cf["heads"], co["heads"]):
                head_diffs.append(state_dict_diff(hf, ho))
            ta_f, ta_o = cf["tail_anchor_model"], co["tail_anchor_model"]
            ta_diffs.append(state_dict_diff(ta_f, ta_o))
            key_diffs.append(max_diff(ta_f.get("key"), ta_o.get("key")))
            anchor_diffs.append(max_diff(ta_f.get("anchor_pool"),
                                         ta_o.get("anchor_pool")))
            cprompt_diffs.append(state_dict_diff(cf.get("prompts"),
                                                 co.get("prompts")))

        # inner 70/30 splits (fork uses int client/task keys -> normalize)
        inner_fork = {str(cid): {str(t): s for t, s in tasks.items()}
                      for cid, tasks in
                      (ckpt.get("data_split_state") or {}).items()}
        inner_official = dump["inner_splits"]
        split_equal = bool(deep_equal(inner_fork, inner_official))
        outer_equal = bool(deep_equal(outer_fork, outer_official))

        comparison = {
            "completed_round_diff": abs(int(ckpt["completed_round"])
                                        - int(dump["completed_round"])),
            "server_model_max_diff": state_dict_diff(ckpt["server_model"],
                                                     dump["server_model"]),
            "global_proto_max_diff": protos_diff(ckpt["global_protos"],
                                                 dump["global_protos"]),
            "temp_proto_max_diff": protos_diff(ckpt.get("temp_protos"),
                                               dump.get("temp_protos")),
            "prompt_max_diff": state_dict_diff(ckpt["server_prompt"],
                                               dump["server_prompt"]),
            "client_prompt_max_diff": (max(cprompt_diffs)
                                       if cprompt_diffs else 0.0),
            "head_max_diff": max(head_diffs),
            "key_max_diff": max(key_diffs),
            "anchor_max_diff": max(anchor_diffs),
            "tail_anchor_state_max_diff": max(ta_diffs) if ta_diffs else 0.0,
            "split_equal": split_equal,
            "outer_split_equal": outer_equal,
            "fix_keys_equal": sorted(map(str, ckpt["fix_keys"]))
                              == sorted(map(str, dump["fix_keys"])),
        }

        # ---------- pass/fail report ----------
        report = []
        for name, diff in comparison.items():
            if name in ("split_equal", "outer_split_equal",
                        "fix_keys_equal"):
                report.append((name, diff is True,
                               0.0 if diff else float("inf"), ""))
            else:
                report.append((name, diff == 0.0, diff, ""))

        print("\n===== official FedTA parity report =====")
        all_ok = True
        for name, ok, diff, note in report:
            status = "PASS" if ok else "FAIL"
            all_ok &= ok
            print(f"[{status}] {name:26s} max_diff={diff}"
                  f"{('  (' + note + ')') if note else ''}")

        result = "PASS" if all_ok else "FAIL"
        passed = all_ok

        fork_record = {
            "run_dir": str(run_dir),
            "completed_round": int(ckpt["completed_round"]),
            "outer_split_hash": hash_obj(outer_fork),
            "inner_split_hash": hash_obj(inner_fork),
            "global_protos_checksum": hash_obj(ckpt.get("global_protos")),
            "global_head_checksum": hash_obj(ckpt.get("global_head")),
            "server_prompt_checksum": hash_obj(ckpt.get("server_prompt")),
            "server_model_checksum": hash_obj(ckpt.get("server_model")),
            "key_checksums": {str(c["id"]): hash_obj(
                c["tail_anchor_model"].get("key"))
                for c in ckpt["clients"]},
            "anchor_pool_checksums": {str(c["id"]): hash_obj(
                c["tail_anchor_model"].get("anchor_pool"))
                for c in ckpt["clients"]},
            "args": ckpt.get("args"),
        }
        official_record = {
            "official_repo": str(official_repo),
            "dump_path": str(dump_path),
            "config_module": dump.get("config_module"),
            "dropped_spliter_kwargs": dump.get("dropped_spliter_kwargs"),
            "dropped_server_kwargs": dump.get("dropped_server_kwargs"),
            "lenient_overrides_absent_from_config":
                dump.get("lenient_overrides_absent_from_config"),
            "completed_round": int(dump["completed_round"]),
            "outer_split_hash": hash_obj(outer_official),
            "inner_split_hash": hash_obj(inner_official),
            "global_protos_checksum": hash_obj(dump.get("global_protos")),
            "global_head_checksum": hash_obj(dump.get("global_head")),
            "server_prompt_checksum": hash_obj(dump.get("server_prompt")),
            "server_model_checksum": hash_obj(dump.get("server_model")),
            "key_checksums": {str(c["id"]): hash_obj(
                c["tail_anchor_model"].get("key"))
                for c in dump["clients"]},
            "anchor_pool_checksums": {str(c["id"]): hash_obj(
                c["tail_anchor_model"].get("anchor_pool"))
                for c in dump["clients"]},
            "official_args": dump.get("official_args"),
        }

        verification = {
            "test": "official_fedta_parity",
            "gate": "Gate 0A: FedSMTA --method fedta must be bit-identical "
                    "to the official FedTA (D=0)",
            "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "result": result,
            "config": {
                "data_name": args.data_name, "method": args.method,
                "seed": args.seed, "rounds": args.rounds,
                "global_epoch": args.global_epoch, "task_num": args.task_num,
                "local_epoch": args.local_epoch,
                "client_num": args.client_num,
                "private_class_num": args.private_class_num,
                "batch_size": args.batch_size,
                "surrogate_num": args.surrogate_num,
                "threshold": args.threshold, "lr": args.lr,
                "deterministic": True, "no_instrumentation": True,
            },
            "fork_run": fork_record,
            "official_run": official_record,
            "comparison": {k: (None if v == float("inf") else v)
                           for k, v in comparison.items()},
            "notes": [
                "accuracy is NOT gating in v1: D=0 over all model states "
                "and both splits implies identical evaluation outputs",
                "RNG states cannot be compared: the official repo has no "
                "checkpoint mechanism",
                "both sides run with cudnn.deterministic=True (fork "
                "--deterministic mirrors the driver)",
                "if tiny nonzero diffs appear, first suspect GPU/operator "
                "nondeterminism and rerun; do NOT loosen the tolerance",
            ],
        }
        out_path = (Path(args.work_dir) / "metrics"
                    / "official_fedta_parity.json")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(verification, f, indent=2, default=str)

        print(f"\nsaved {out_path}")
        print("\nRESULT:", result if all_ok else
              "FAIL (the fedta path diverges from the official FedTA; "
              "compare the checksums in the JSON to locate the first "
              "diverging component)")
    finally:
        if args.keep_driver or not passed:
            print(f"[debug] keeping parity driver artifacts in "
                  f"{official_repo}: {driver_path.name}, "
                  f"{payload_path.name}, {dump_path.name}")
        else:
            for p in (driver_path, payload_path, dump_path):
                try:
                    p.unlink()
                except OSError:
                    pass

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
